apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-demo-5
  labels:
    app: golang-demo-5
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: golang-demo-5
  template:
    metadata:
      labels:
        app: golang-demo-5
    spec:
      containers:
      - name: golang-demo-5
        image: "ironcore864/golang-demo:{{ .Chart.AppVersion }}"
        ports:
        - containerPort: 8080
